### ISSUE TITLE
Binary Search

### ISSUE THREAD

**Issue by deep846** [Hacktoberfest-2021/2022_problem#1]
Write a code for binary search

**Comment by AkshayGidwani405** [comment]
Hey @deep846! I can contribute to this issue. Please assign me.

**Comment by Deep8764** [comment]
can you assign me this problem.

**Comment by AkshayGidwani405** [comment]
Thanks for assigning. @deep846 Just a kind suggestion, please update the README.md as pe Hacktoberfest guidelines else the PR raised are excluded by Hacktoberfest. Thankyou.
