### ISSUE TITLE
Infix to postfix conversion.

### ISSUE THREAD

**Issue by deep846** [Hacktoberfest-2021/2022_problem#7]

**Comment by Deep8764** [comment]
I want to solve this issue using cpp.

**Comment by MayankUghade** [comment]
@deep846 even i want to contribute, assign me as well.

**Comment by anshul-kr1** [comment]
I want to solve this using Java. Assign this to me.

**Comment by vaibhv232** [comment]
assign me this task

**Comment by Nimesh-21** [comment]
Can you please assign this to me? I am new to open source.

**Comment by deepakchoursiya** [comment]
hey @deep846  can you assign me this task
